spring:
  application:
    name: keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-realm-dev
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  server-url: "http://localhost:8080"
  realm-name: "spring-boot-realm-dev"
  realm-master: "master"
  admin-cli: "admin-cli"
  user-console: "admin"
  user-password: "admin"
  client-secret: ""

server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: auth-service-api-gateway
      principal-attr: preferred_username

# Colour ANSI logs Options: ALWAYS, DETECT or NEVER
spring.output.ansi.enabled: ALWAYS

logging:
  level:
    org:
      keycloak: DEBUG

